### ISSUE TITLE
v5.0 to v5.5 are broken (or missing the extra files)

### ISSUE THREAD

**Issue by k-takata** [vim/vim-history#2]
As I wrote in README.md, I created the history from the tarballs at the Vim FTP site.
However, the tag `v5.0` doesn't contain some files from `vim-5.0.tar.gz` by mistake.
Moreover, `vim-5.0.tar.gz` to `vim-5.5.tar.gz` don't contain the source files for Windows and other platforms (unlike `vim-4.6.tar.gz`), because they are in the separate packages: http://ftp.vim.org/pub/vim/extra/ . (Unfortunately I didn't know that.) So the extra files are missing from `v5.0` to `v5.5`.

I want to fix them, but it requires rewrite of the history (and `git push -f`). Is it acceptable?

**Comment by chrisbra** [comment]
from my side this is okay

**Comment by k-takata** [comment]
I have written the history and done `git push -f`.
The old `master` and `vim-5-8` branches were renamed to `old-master` and `old-vim-5-8`.

**Comment by k-takata** [comment]
To update a local repository:

```
$ git fetch --tags
$ git reset --hard @{u}
```

Or it might be easier to clone newly.

**Comment by k-takata** [comment]
If there is someone already uses https://github.com/vim/vim-history#merge-the-whole-history, and want to keep the same local repository, try this:

```
git fetch vim-history --tags
git replace --graft v7.0001 vim-6-3-004 -f
```

**Comment by k-takata** [comment]
Just for my note, this is how I fixed the history:

```
git checkout -b vim-5-0 v5.0; (unpack vim-5.0.tar.gz, vime-5.0.tar.gz and commit)
git checkout -b vim-5-1 v5.1; (unpack vime-5.1.tar.gz and commit)
git checkout -b vim-5-2 v5.2; (commit extra files for 5.2 [1])
git checkout -b vim-5-3 v5.3; (unpack vim-5.3-extra.tar.gz and commit)
git checkout -b vim-5-4 v5.4; (unpack vim-5.4-extra.tar.gz and commit)
git checkout -b vim-5-5 v5.5; (unpack vim-5.5-extra.tar.gz and commit)

git replace --graft vim-5-0 v4.6
git replace --graft vim-5-1 vim-5-0
git replace --graft vim-5-2 vim-5-1
git replace --graft vim-5-3 vim-5-2
git replace --graft vim-5-4 vim-5-3
git replace --graft vim-5-5 vim-5-4
git replace --graft vim-5-5-import^ vim-5-5

git tag -f v5.0 vim-5-0
git tag -f v5.1 vim-5-1
git tag -f v5.2 vim-5-2
git tag -f v5.3 vim-5-3
git tag -f v5.4 vim-5-4
git tag -f v5.5 vim-5-5

git filter-branch -- --all
```

[1] `vim-5.2-extra.tar.gz` doesn't exist. So I unpacked `vim-5.3-extra.tar.gz` then applied `vim-5.2-5.3-extra.diff.gz` reversely.
